from typing import List, Optional

Matrix = List[List[int]]

def simple_bit_pack(polynomial: List[int], end: int) -> bytes: ...

def simple_bit_unpack(byte_string: bytes, end: int) -> List[int]: ...

def bit_pack(polynomial: List[int], start: int, end: int) -> bytes: ...

def bit_unpack(byte_string: bytes, start: int, end: int) -> List[int]: ...

def hint_bit_pack(polynomial_vector: Matrix, K: int, OMEGA: int) -> bytes: ...

def hint_bit_unpack(byte_string: bytes, K: int, OMEGA: int) -> Matrix | None: ...
