from typing import List, Optional

def bits_to_bytes(bit_array: List[int]) -> bytes: ...

def bytes_to_bits(byte_array: bytes) -> List[int]: ...

def byte_encode(f: List[int], d: int) -> bytes: ...

def byte_decode(byte_array: bytes, d: int) -> List[int]: ...

def compress(x: List[int],d: int,q: Optional[int] = 3329) -> List[int]: ...

def decompress(y:List[int], d:int, q: Optional[int] = 3329) -> List[int]: ...

