from typing import List, Tuple

def shake128(ctx: List[bytes], byte_lengths: List[int]) -> bytes: ...

def sha3_512(ctx: bytes) -> Tuple[bytes, bytes]: ...

def sha3_256(ctx: bytes) -> bytes: ...

def prf(ctx: bytes, b: bytes, eta: int) -> bytes: ...

def shake256(ctx: bytes) -> bytes: ...

def slh_H_msg(r: bytes, public_key_seed: bytes, public_key_root: bytes, message: bytes) -> bytes: ...

def slh_H(public_key_seed: bytes, address: bytes, message: bytes) -> bytes: ...

def slh_F(public_key_seed: bytes, address: bytes, message: bytes) -> bytes: ...

def slh_T(public_key_seed: bytes, address: bytes, message: List[bytes]) -> bytes: ...

def slh_prf(public_key_seed: bytes, private_key_seed: bytes, address: bytes) -> bytes: ...

def slh_prf_msg(public_key_seed: bytes, private_key_seed: bytes, address: bytes, message: bytes) -> bytes: ...
