from typing import List, Tuple

def shake128(ctx: List[bytes], byte_lengths: List[int]) -> bytes: ...

def sha3_512(ctx: bytes) -> Tuple[bytes, bytes]: ...

def sha3_256(ctx: bytes) -> bytes: ...

def prf(ctx: bytes, b: bytes, eta: int) -> bytes: ...

def shake256(ctx: bytes) -> bytes: ...
