from typing import Tuple


def power2_round(r: int, Q: int, D: int) -> Tuple[int, int]: ...

def decompose(r: int, Q: int, GAMMA_2: int) -> Tuple[int, int]: ...

def high_bits(r: int, Q: int, GAMMA_2: int) -> int: ...

def low_bits(r: int, Q: int, GAMMA_2: int) -> int: ...

def mod_symmetric(r: int, Q: int) -> int: ...

def make_hint(z: int, r: int, Q: int, GAMMA_2: int) -> bool: ...

def use_hint(h: bool, r: int, Q: int, GAMMA_2: int) -> int: ...
