from typing import Tuple, List

Matrix = List[List[int]]

class Encodings:

    def __init__(self, const) -> None:
        self.const = None
        ...

    def public_key_encode(self, ro: bytes, t1: Matrix) -> bytes: ...

    def public_key_decode(self, public_key: bytes) -> Tuple[bytes, Matrix]: ...

    def private_key_encode(self, r0: bytes, k: bytes, tr: bytes, s1: Matrix, s2: Matrix, t0: Matrix) -> bytes: ...

    def private_key_decode(self, d: bytes) -> Tuple[bytes, bytes, bytes, Matrix, Matrix, Matrix]: ...
    
    def sign_encode(self, c_hat: bytes, z: Matrix, h: Matrix) -> bytes: ...

    def sign_decode(self, sigma: bytes) -> Tuple[bytes, Matrix, Matrix]: ...

    def w1_encode(self, w1: Matrix) -> bytes: ...
