from typing import List, Tuple, Any
from core.utils.overflow.stubborn import NTTModified, VectorNTT

Matrix = List[List[int]]

class Sample:
    const: Any

    def __init__(self, const) -> None: ...

    def sample_in_ball(self, seed: bytes) -> NTTModified: ...

    def rej_ntt_polynomial(self, seed: bytes) -> NTTModified: ...

    def rej_bounded_polynomial(self, seed: bytes) -> NTTModified: ...

    def expand_A(self, seed: bytes) -> List[VectorNTT]: ...

    def expand_S(self, seed: bytes) -> Tuple[VectorNTT, VectorNTT]: ...

    def expand_mask(self, seed: bytes, coefficient: int) -> VectorNTT: ...

